import turtle
window = turtle.Screen()
window.bgcolor("forestgreen")
window.setup(600,600)
t = turtle.Turtle()
t.pencolor("red")
t.penup()
t.goto(0,0)
t.seth(90)
t.hideturtle()
t.pendown()
t.forward(200)
t.seth(315)
t.forward(100)
t.seth(225)
t.pencolor("black")
t.forward(100)
t.seth(180)
t.penup()
t.forward(100)
t.write("Happy Birthday Javen!",align="right",font=("Arial",10))
window.mainloop()