no1=int(input("What is number #1?")) 
no2=int(input("What is number #2?"))
no3=int(input("What is number #3?"))
no4=int(input("What is number #4?"))
no5=int(input("What is number #5?"))
print("The sum of the numbers is", str(no1+no2+no3+no4+no5))